# Site settings
title: Unwronging instincts  
email: mehra.vatsal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Learning to write by exploring topics in social science, philosophy and other
    interesting aspects of our carbon based lives. 
    
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rdbcasillas.github.io" # the base hostname & protocol for your site
twitter_username: rdbcasillas   
github_username:  rdbcasillas   

# plugins
gems: [jekyll-twitter-plugin]

permalink: none
