# Site settings
title: Unwronging instincts  
email: mehra.vatsal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Learning to write by exploring topics in social science, philosophy and other
    interesting aspects of our carbon based lives. 
    
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rdbcasillas.github.io" # the base hostname & protocol for your site
twitter_username: rdbcasillas   
github_username:  rdbcasillas   
# Build settings

# plugins
plugins_dir: 
    - jekyll-twitter-plugin

encoding: UTF-8
markdown: kramdown
highlighter: rouge

permalink: none
